.editorconfig
CommandDotNet.Tests/NestedCommandsTest.cs
CommandDotNet.Tests/Parsing/ArgumentParserTests.cs
CommandDotNet.Tests/Parsing/StringValueParserTests.cs
CommandDotNet.Tests/TestCases/MyTestApp.TestMethodParams.Input.json
CommandDotNet/ArgumentParser.cs
CommandDotNet/Parsing/SingleValueParser.cs

Enables proper usage of arguments which are supposed to be multiple text tokens, seperated by spaces.

Brackets parsing error fix

---

CommandDotNet.Tests/BddTests/Framework/ScenarioThen.cs
CommandDotNet.Tests/BddTests/ScenarioTests.cs
CommandDotNet.Tests/BddTests/TestScenarios/FlagScenarios.cs
CommandDotNet.Tests/BddTests/TestScenarios/GlobalOptionsInheritedScenarios.cs
CommandDotNet.Tests/BddTests/TestScenarios/GlobalOptionsScenarios.cs
CommandDotNet.Tests/BddTests/TestScenarios/OptionalParamsScenarios.cs
CommandDotNet.Tests/Utils/TestOutputs.cs
CommandDotNet/Extensions/ObjectExtensions.cs
CommandDotNet/HelpGeneration/DetailedHelpTextProvider.cs
CommandDotNet/ValueMachine.cs
README.md

Added OutputsStrict test option to assert no
unexpected methods were called.

3 Add bdd tests for global options: help & exec

---

CommandDotNet.Tests/CommandDotNet.Tests.csproj
CommandDotNet.Tests/FeatureTests/Arguments/AppsSettings_BoolMode.cs
CommandDotNet.Tests/FeatureTests/Arguments/DefaultArgumentMode.cs
CommandDotNet.Tests/FeatureTests/Arguments/MixedDefinedAs_MethodParamsAndArgModel.cs
CommandDotNet.Tests/FeatureTests/Arguments/NestedArgModel.cs
CommandDotNet.Tests/FeatureTests/Arguments/Operands_DefinedAsArgModel_Defaults.cs
CommandDotNet.Tests/FeatureTests/Arguments/Operands_DefinedAsArgModel_NoDefaults.cs
CommandDotNet.Tests/FeatureTests/Arguments/Operands_DefinedAsMethodParams_Defaults.cs
CommandDotNet.Tests/FeatureTests/Arguments/Operands_DefinedAsMethodParams_NoDefaults.cs
CommandDotNet.Tests/FeatureTests/Arguments/Options_DefinedAsArgModel_Defaults.cs
CommandDotNet.Tests/FeatureTests/Arguments/Options_DefinedAsArgModel_NoDefaults.cs
CommandDotNet.Tests/FeatureTests/Arguments/Options_DefinedAsMethodParams_Defaults.cs
CommandDotNet.Tests/FeatureTests/Arguments/Options_DefinedAsMethodParams_NoDefaults.cs
CommandDotNet.Tests/FeatureTests/ConstructorOptions.cs
CommandDotNet.Tests/FeatureTests/ConstructorOptionsInherited.cs
CommandDotNet.Tests/FeatureTests/NestedCommand.cs
CommandDotNet.Tests/FeatureTests/VersionOption.cs
CommandDotNet.Tests/ScenarioFramework/ScenarioTestBase.cs
CommandDotNet.Tests/TestAppSettings.cs
CommandDotNet.Tests/Utils/AppRunnerTestExtensions.cs
CommandDotNet.sln.DotSettings
CommandDotNet/Models/AppSettings.cs
CommandDotNet/TypeDescriptors/ArgumentTypeDescriptors.cs

- prevents tight coupling to the feature
- reduces the noise in help expectations

create test default for AppSettings w/ Version disabled

---

CommandDotNet.Example/Program.cs

to examine how different shells parse quoted strings
shell - git bash on Win 10
shell - cmd.exe on Win 10
this is how the arguments are passed into our .net process.

introduce echo-args in example to test shell arg parsing

---

CommandDotNet.Tests/FeatureTests/Arguments/Operands_DefinedAsArgModel_Defaults.cs
CommandDotNet.Tests/FeatureTests/Arguments/Options_DefinedAsArgModel_Defaults.cs
CommandDotNet/Extensions/EnumerableExtensions.cs
CommandDotNet/HelpGeneration/DetailedHelpTextProvider.cs
CommandDotNet/StringExtensions.cs

ex: [System.Collections.Generic.List`1[System.String]]
is now: [blue,red]
also fixed issue where help was generating every segment
for an argument 2+{arg count} resulting in O(N²).
Typically not a big deal since arguments won't be big
numbers, but every bit counts when you want a fast
console app.

Fix default list values in Detailed Help

---

CommandDotNet.Tests/FeatureTests/Arguments/StringCtorObjectsAsArguments.cs
CommandDotNet/TypeDescriptors/ArgumentTypeDescriptors.cs
CommandDotNet/TypeDescriptors/StringCtorTypeDescriptor.cs
README.md

@bilal-fazlani I got this idea from https://github.com/dotnet/command-line-api.  Thanks to the TypeDescriptors, it's was 15 minutes of coding.   That repo may be the future but they're still some things, like subcommands, and operands have to be named.  
Anyway, this enables FileInfo, DirectoryInfo, etc as parameters types.  Pretty cool I think.

any type w/ a string ctor can be converted for arguments

---

CommandDotNet.Example/Directives.cs
CommandDotNet.Example/Program.cs

[debug] will print the current process id and wait for
a debugger to attach
[parse] will print the args as parsed by the shell
this is not intended to be as feature rich as theirs
but just borrowing their naming convention

add System.CommandLine style directives

---

CommandDotNet.Tests/FeatureTests/Help/GeneralHelpTests.cs
CommandDotNet/ArgumentTemplate.cs
CommandDotNet/Help/HelpMiddleware.cs
CommandDotNet/IOption.cs
CommandDotNet/Option.cs
CommandDotNet/Parsing/CommandParser.cs

didn't add to the template because that is included
in the help output.
Removed Option.Symbol because it was only useful
for help and that's no longer necessary with the new
design

support '-?' for help

---

CommandDotNet.Example/DocExamples/RocketLauncher.cs
CommandDotNet.Tests/FeatureTests/Arguments/BasicParseScenarios.cs
CommandDotNet.Tests/FeatureTests/CaseTests.cs
CommandDotNet/ArgumentTemplate.cs
CommandDotNet/ClassModeling/Definitions/DefinitionMappingExtensions.cs
CommandDotNet/Help/BasicHelpTextProvider.cs
CommandDotNet/Help/DetailedHelpTextProvider.cs
CommandDotNet/Help/HelpMiddleware.cs
CommandDotNet/Operand.cs
CommandDotNet/Option.cs
CommandDotNet/OptionAttribute.cs

since either long or short name can be null but at least
one has to be populated, this let's .Name be Long if
populated else Short.  Name will always have a value for
any argument.  This is useful for error reporting, logging
and help

bring back Option.LongName then Option.Name=>Long??Short

---

CommandDotNet.Example/CommandDotNet.Example.csproj
CommandDotNet.Example/Program.cs
CommandDotNet.GitHubReleases/AlertOnNewerReleaseMiddleware.cs
CommandDotNet.GitHubReleases/CommandDotNet.NewerReleasesAlerts.csproj
CommandDotNet.GitHubReleases/GitHubMiddleware.cs
CommandDotNet.Tests/CommandDotNet.Tests.csproj
CommandDotNet.Tests/FeatureTests/NewReleaseAlerts/NewReleaseAlertOnGitHubTests.cs
CommandDotNet.sln
CommandDotNet/AppConfigBuilder.cs
CommandDotNet/Builders/VersionInfo.cs
CommandDotNet/Builders/VersionMiddleware.cs
CommandDotNet/Directives/DebugDirective.cs
CommandDotNet/Directives/Debugger.cs

@bilal-fazlani  Another example of adding middleware.  I made this a separate project because of the external dependencies.  When #154 is resolved, we can make this available as another nuget package.

feature: alert when newer releases of app exist on github

---

CommandDotNet/AppConfigBuilder.cs
CommandDotNet/Directives/DebugDirective.cs
CommandDotNet/Directives/Debugger.cs
CommandDotNet/Execution/AppConfig.cs

the token can be used by the app to trigger
a cancellation of the process.
This creates a well known single token that
all middleware can reference.
A feature will be added later to enable
cancellation using this token

add well-known cancellation token

---

CommandDotNet/CommandContext.cs

It can be used for the Middleware interceptor methods and
commonly used classes should be in root namespace to
simplify use and discovery for devs

rehome command context

---

CommandDotNet/ClassModeling/ClassModelingMiddleware.cs
CommandDotNet/ClassModeling/Definitions/ClassCommandDef.cs
CommandDotNet/ClassModeling/Definitions/DefinitionMappingExtensions.cs
CommandDotNet/ClassModeling/Definitions/DelegateCommandDef.cs
CommandDotNet/ClassModeling/Definitions/ICommandDef.cs
CommandDotNet/ClassModeling/Definitions/IMethodDef.cs
CommandDotNet/ClassModeling/Definitions/MethodCommandDef.cs
CommandDotNet/ClassModeling/Definitions/MethodDef.cs
CommandDotNet/ClassModeling/Definitions/NullCommandDef.cs
CommandDotNet/ClassModeling/Definitions/NullMethodDef.cs
CommandDotNet/ClassModeling/ModelValidator.cs
CommandDotNet/Execution/IInvocation.cs
CommandDotNet/Execution/InvocationContext.cs
CommandDotNet/Extensions/EnumerableExtensions.cs
CommandDotNet/Extensions/TypeExtensions.cs

Changed the name of MiddlewareMethod to Interceptor.
I think this better describes how it's thought of and
reduces confusion with other middleware.
IInvocation.Invoke added a 'next' param which
will be null for the main command but populated
for interceptors
Discovered a possible bug where if someone
reassigned the invocations on the InvocationContext
they wouldn't have been honored because
we had to get the invocation from the ICommandDef.

make InterceptorInvocation publicly available

---

CommandDotNet/DependencyResolverExtensions.cs

The bug was caused by the TryResolve ext method
returning true when no instance was resolved.
#169 is already fixed in V3 because it will use
the containers TryResolve which is expected
to behave correctly.

fixes #169, null ref creating instance of fluent validator

---

CommandDotNet.GitHubReleases/CommandDotNet.NewerReleasesAlerts.csproj
CommandDotNet.TestTools/CommandDotNet.TestTools.csproj
CommandDotNet/CommandDotNet.csproj
deploy.sh

monorepo deploy uses correct project ref versions in nuspec
> nuget cannot determine the correct project semver from the files in source because the semver is stored in git tags.
> this commit will fix version references in the nuspec file before publishing.
consistent nuget in proj files - include dbg and symbols

monorepo deploy

---

CommandDotNet.Tests/FeatureTests/Arguments/DefaultArgumentModeTests.cs
CommandDotNet.Tests/FeatureTests/ClassCommands/DuplicateAliasDetectedTests.cs
CommandDotNet.Tests/FeatureTests/ClassCommands/InterceptorExecutionTests.cs
CommandDotNet.Tests/FeatureTests/ClassCommands/InterceptorExecutionWithDefaultMethodTests.cs
CommandDotNet.Tests/FeatureTests/ClassCommands/InterceptorExecutionWithInheritedOptionsTests.cs
CommandDotNet.Tests/FeatureTests/Prompting/PromptForMissingArgumentTests.cs
CommandDotNet/ClassModeling/Definitions/DefinitionMappingExtensions.cs
CommandDotNet/Command.cs
CommandDotNet/CommandExtensions.cs
CommandDotNet/Help/BasicHelpTextProvider.cs
CommandDotNet/Help/HelpTextProvider.cs
CommandDotNet/Option.cs
CommandDotNet/OptionAttribute.cs

Inherited options should only be used for subcommands
- Move logic from mapping extensions to Command to ensure
inherited options are added to subcommands
- obsolete Inherited for AssignToExecutableSubcommands
as a more descriptive name for Option and
OptionAttribute
- update help, removing the clunky footnote concept.
since there will only be confusion when a default
command also has interceptor options, adding a new
options section is clear enough.
- leaving the term Inherited in the tests and comments
as it is more terse than AssignToExecutableSubcommands
and added Inherited term to the xml docs to make
the connection easier to see.

Command.Options does not include inherited options

---

.travis.yml
publish_doc.sh

using a docker image to build mkdocs ensures the same
versions of python, mkdocs & material themes are used on
all machines and removes the need to install locally

publish_doc.sh - use docker and support run from local dev

---

CommandDotNet/CommandDotNet.csproj

With this mapping stacktraces do not show the path to the file on the file system (during compile time) that caused the exception.
Instead of e.g. /home/bilal-fazlani/.../CommandDotnet/AppRunner.cs.... the stacktrace shows CommandDotNet/AppRunner.cs
That makes it a lot prettier and less confusing for less technical users.

Added AppOutputBase and PathMap

---

CommandDotNet.Tests/UnitTests/Extensions/ArgumentExtensionTests.cs
CommandDotNet/Builders/VersionMiddleware.cs
CommandDotNet/ClassModeling/Definitions/DefinitionMappingExtensions.cs
CommandDotNet/Command.cs
CommandDotNet/Help/HelpMiddleware.cs
CommandDotNet/Operand.cs
CommandDotNet/Option.cs

this makes it easier to add them in build events
and we can ensure the command is the one they
are added to

don't require a parent command for arguments

---

CommandDotNet.Tests/FeatureTests/Arguments/AppsSettingsBoolModeTests.cs
CommandDotNet.Tests/FeatureTests/Arguments/EnumerableArgTypesTests.cs
CommandDotNet.Tests/FeatureTests/Arguments/MixedDefinedAs_MethodParamsAndArgModel_Tests.cs
CommandDotNet.Tests/FeatureTests/Arguments/NestedArgModelTests.cs
CommandDotNet.Tests/FeatureTests/ClassCommands/InterceptorExecutionWithDefaultMethodTests.cs
CommandDotNet.Tests/FeatureTests/ClassCommands/InterceptorExecutionWithInheritedOptionsTests.cs
CommandDotNet.Tests/FeatureTests/Help/ArgumentAttributesHelpTests.cs
CommandDotNet.Tests/FeatureTests/Help/ExpandArgumentsInUsageTests.cs
CommandDotNet.Tests/FeatureTests/ParameterResolverTests.cs
CommandDotNet/Help/AppHelpSettings.cs
CommandDotNet/Help/HelpTextProvider.cs
docs/DefiningCommands/argument-collections.md
docs/DefiningCommands/arguments.md
docs/Extensibility/help.md

[options] [arguments] becomes
[options] < arg1 > < arg2 > [< optionalArg >]
closes #186

Expand arguments in Usage example

---

CommandDotNet.Example/CommandDotNet.Example.csproj
CommandDotNet.FluentValidation/CommandDotNet.FluentValidation.csproj
CommandDotNet.Tests/CommandDotNet.Tests.csproj

add FluentValidation.Attributes dependency to keep using
ValidatorAttribute
https://docs.fluentvalidation.net/en/latest/upgrading-to-8.html#validatorattribute-and-attributedvalidatorfactory-have-been-moved-to-a-separate-package

upgrade FluentValidation to v8

---

CommandDotNet.Tests/FeatureTests/ArgumentDefaults/DefaultFromAppSettingsTests.cs
CommandDotNet.Tests/FeatureTests/ArgumentDefaults/DefaultFromEnvVarsTests.cs
CommandDotNet.Tests/FeatureTests/ArgumentDefaults/UseDefaultsFromConfigTests.cs
CommandDotNet.Tests/FeatureTests/EnabledMiddlewareScenarios/SetDefaultsTestMiddleware.cs
CommandDotNet/AppRunnerConfigExtensions.cs
CommandDotNet/ArgumentArity.cs
CommandDotNet/ArgumentDefault.cs
CommandDotNet/Builders/ArgumentDefaults/DefaultSources.cs
CommandDotNet/Builders/ArgumentDefaults/SetArgumentDefaultsMiddleware.cs
CommandDotNet/ClassModeling/BindValuesMiddleware.cs
CommandDotNet/ClassModeling/Definitions/DefinitionMappingExtensions.cs
CommandDotNet/ClassModeling/Definitions/IArgumentDef.cs
CommandDotNet/ClassModeling/Definitions/ParameterArgumentDef.cs
CommandDotNet/ClassModeling/Definitions/PropertyArgumentDef.cs
CommandDotNet/Help/HelpTextProvider.cs
CommandDotNet/IArgument.cs
CommandDotNet/Operand.cs
CommandDotNet/Option.cs
CommandDotNet/Prompts/ValuePromptMiddleware.cs
docs/Middleware/default-values-from-config.md

This makes it easy to track the source of default values.
Middleware and Help providers can take advantage of this
for logging and troubleshooting.

add DefaultValue type with source and key

---

CommandDotNet.GitHubReleases/AlertOnNewerReleaseMiddleware.cs
CommandDotNet.Tests/CommandDotNet.NewerReleasesAlerts/NewReleaseAlertOnGitHubTests.cs
CommandDotNet/Builders/AppInfo.cs
CommandDotNet/Builders/VersionInfo.cs
CommandDotNet/Builders/VersionMiddleware.cs
CommandDotNet/Help/HelpBuilderExtensions.cs

AppInfo will return the correct file name and logic is now
in one place to determine if dotnet, self-contained.exe or
regular .exe

replace VersionInfo w/ AppInfo. ++ self-contained.exe logic

---

CommandDotNet.Tests/FeatureTests/TypoSuggestions_GetSuggestions_Tests.cs
CommandDotNet/Parsing/TypoSuggestionsMiddleware.cs

i.e. nameuser -> username or treework -> worktree

check mis-ordered keywords in typo suggestions

---

CommandDotNet.Tests/CommandDotNet.CommandLogger/CommandLoggerTests.cs
CommandDotNet.Tests/FeatureTests/Arguments/Options_Name_Legacy_Tests.cs
CommandDotNet.Tests/FeatureTests/Arguments/Options_Name_New_Tests.cs
CommandDotNet/AppSettings.cs
CommandDotNet/ClassModeling/Definitions/DefinitionMappingExtensions.cs
CommandDotNet/OptionAttribute.cs
docs/DefiningCommands/arguments.md

Add setting so ShortName can be set without losing the
default long name from the property or parameter.
This will become the default behavior in the next major
version

#183 - ShortName does not remove LongName setting

---

CommandDotNet.Tests/CommandDotNet.CommandLogger/CommandLoggerTests.cs
CommandDotNet/Execution/CommandLoggerMiddleware.cs

the default behavior is only to output when the cmdlog
directive is specified.

fix commad logger logging without [cmdlog] specified

---

CommandDotNet.Tests/FeatureTests/Arguments/ArgumentSeparatorTests.cs
CommandDotNet.Tests/FeatureTests/Arguments/BasicParseTests.cs
CommandDotNet/AppSettings.cs
CommandDotNet/ArgumentSeparatorStrategy.cs
CommandDotNet/ClassModeling/Definitions/DefinitionMappingExtensions.cs
CommandDotNet/Command.cs
CommandDotNet/CommandAttribute.cs
CommandDotNet/CommandExtensions.cs
CommandDotNet/Parsing/CommandParser.cs
CommandDotNet/Parsing/ParseResult.cs
docs/DefiningCommands/argument-separator.md
docs/DefiningCommands/commands.md
docs/ReleaseNotes/CommandDotNet.md
docs/ReleaseNotes/roadmap.md
mkdocs.yml

breaking:
- Change ParseResult RemainingOperands & SeparatedArguments
to IReadOnlyCollection<string>
other:
- Add ArgumentSeparatorStrategy {PassThru,EndOfOptions}
- Override arg parsing defaults via CommandAttribute with
.IgnoreUnexpectedOperands & .ArgumentSeparatorStrategy
- update parser to honor ArgumentSeparatorStrategy

support `--` as end-of-options indicator

---

CommandDotNet.Tests/FeatureTests/ExceptionHandlingTests.cs
CommandDotNet/AppRunner.cs
CommandDotNet/Execution/MiddlewareSteps.cs
CommandDotNet/HandleErrorDelegate.cs
docs/Diagnostics/exceptions.md
docs/ReleaseNotes/CommandDotNet.md

this is a simpler implementation because it doesn't require
the consumer to inject in the pipeline. The delegate is
only called if an exception is thrown and it is called
outside of the async pipeline so it will have been
unwrapped.

implement .UseErrorHandler w/ HandleErrorDelegate

---

CommandDotNet.Example/Examples.cs
CommandDotNet.Example/InteractiveMiddleware.cs
CommandDotNet.Example/InteractiveSession.cs
CommandDotNet.Example/Program.cs
CommandDotNet.Tests/FeatureTests/CancellationTokenTests.cs
CommandDotNet.Tests/FeatureTests/ParameterResolverTests.cs
CommandDotNet/AppConfigBuilder.cs
CommandDotNet/AppRunnerConfigExtensions.cs
CommandDotNet/CommandContext.cs
CommandDotNet/Diagnostics/DebugDirective.cs
CommandDotNet/Execution/AppConfig.cs
CommandDotNet/Execution/CancellationHandlers.cs
CommandDotNet/Execution/CancellationMiddleware.cs
CommandDotNet/Execution/ExecutionMiddlewareExtensions.cs
CommandDotNet/Execution/MiddlewareSteps.cs
CommandDotNet/Extensions/DisposableAction.cs
CommandDotNet/Prompts/ValuePromptMiddleware.cs
docs/OtherFeatures/cancellation.md
docs/ReleaseNotes/CommandDotNet.md
mkdocs.yml

- moved CancellationToken from AppConfig
- added InteractiveSession example to Example app
- CancellationHandlers handles nested runs
- increased test coverage

move CancellationToken to CommandContext, enable sessions

---

CommandDotNet.TestTools/AppRunnerTestExtensions.cs
CommandDotNet.Tests/FeatureTests/ParseDirective/ParseReporter_DefaultValues_Tests.cs
CommandDotNet.Tests/FeatureTests/ParseDirective/ParseReporter_InputValues_Tests.cs
CommandDotNet.Tests/FeatureTests/ParseDirective/ParseReporter_Structure_Tests.cs
CommandDotNet/Diagnostics/CommandLogger.cs
CommandDotNet/Diagnostics/Parse/ParseReporter.cs
CommandDotNet/Diagnostics/ParseDirective.cs

this shows the command line before the .net process split
it into the `string[] args`. It can help to troubleshoot
issues others are having with the parsing

add [parse:raw] to show Environment.CommandLine

---

CommandDotNet.Example/Examples.cs
CommandDotNet.Tests/AppRunnerBuilderExtensions.cs
CommandDotNet.Tests/FeatureTests/Help/CommandTemplatesTests.cs
CommandDotNet.Tests/FeatureTests/Help/UsageAppNameStylesTests.cs
CommandDotNet/Help/HelpTextProvider.cs
docs/Commands/commands.md
docs/Help/help.md

keeping %UsageAppName% for backwards compatibility but
removing all references to it.
adding OnCommandCreated test help that I may move to
TestTools to make it easier to update commands for tests.

add %CmdPath% and %AppName% template variables for cmd help

---

CommandDotNet.Tests/FeatureTests/ClassCommands/SubCommandTests.cs
CommandDotNet.Tests/FeatureTests/ParseDirective/ParseDirectiveVerifier.cs
CommandDotNet/Help/HelpMiddleware.cs
CommandDotNet/TypeDescriptors/DelegatedTypeDescriptor.cs

This is the way all other programs work. Help middleware
will only return Success if help was requested.

exitcode=1 when help shown for non-executable command

---

CommandDotNet.Tests/FeatureTests/ParseTests/BasicParseTests.cs
CommandDotNet.Tests/FeatureTests/SuggestionRankingExtensionsTests.cs
CommandDotNet.Tests/FeatureTests/Suggestions/AllowedValuesTypoSuggestionsTests.cs
CommandDotNet.Tests/FeatureTests/Suggestions/OptionAndSubcommandTypoSuggestionsTests.cs
CommandDotNet/Parsing/Typos/SuggestionRankingExtensions.cs
CommandDotNet/Parsing/Typos/TypoSuggestionsMiddleware.cs

Added test to ensure empty string can be passed as an
argument value for core functionality.
Fix bug in TypoSuggest that threw an exception when
the token value was an empty string. Empty string will
skip suggestions and the error will be shown to the
user

verify empty string supported as argument value

---

CommandDotNet/Diagnostics/ExceptionExtensions.cs
CommandDotNet/Diagnostics/NonSerializableWrapper.cs

This is a problem with older .net frameworks where items
added to ex.Data must be serializable.  That was intended
to support remoting which is not supported in .net core
fixes #331

fix cases where adding cmdctx to ex.Data throws ex

---

CommandDotNet/Builders/AppInfo.cs
CommandDotNet/Execution/AppConfig.cs
CommandDotNet/Extensions/ObjectExtensions.cs

And make ToStringFromPublicProperties public for cases
where a class does not yet use it.
Fix a possible format bug in AppConfig.ToString

Make it easy to print AppInfo

---

CommandDotNet/Builders/ArgumentDefaults/DefaultSources.cs
docs/ArgumentValues/default-values-from-config.md
docs/ReleaseNotes/CommandDotNet.md

This will make it easier to reuse the logic for other
configuration sources like .net core configs.
Add examples to docs and update release notes
Add xmldocs for the public DefaultSources members

expose DefaultSources.GetValueFunc for host apps

---

CommandDotNet.Tests/FeatureTests/ArgumentDefaults/DefaultFromMultipleSourcesTests.cs
CommandDotNet.Tests/FeatureTests/Arguments/BigArgumentsSetsTests.cs
CommandDotNet.Tests/FeatureTests/EnabledMiddlewareScenarios/SetDefaultsTestMiddleware.cs
CommandDotNet/Builders/ArgumentDefaults/SetArgumentDefaultsMiddleware.cs
CommandDotNet/ClassModeling/BindValuesMiddleware.cs
CommandDotNet/Tokens/TokenizerPipeline.cs

- improves performance
- in SetArgumentDefaultsMiddleware could prevent
cases where callbacks are filtered out

favor Concat over Union where possible

---

CommandDotNet.Tests/UnitTests/TypeDescriptors/StringCtorTypeDescriptorTest.cs
CommandDotNet/TypeDescriptors/ComponentModelTypeDescriptor.cs
CommandDotNet/TypeDescriptors/StringCtorTypeDescriptor.cs
docs/Arguments/argument-types.md

string ctor and static Parse methods were supported,
but now the methods can contain additional optional params

support types with string ctor/Parse with optional params

---

README.md
docs/GettingStarted/getting-started-100-calculator.md

Correcting `application` to `application` in `README.md` and `getting-started-100-calculator.md`.

Correcting typos of `application`

---

.github/workflows/release.yml
.github/workflows/test.yml
CommandDotNet.NewerReleasesAlerts/AlertOnNewerReleaseMiddleware.cs
CommandDotNet.TestTools/Scenarios/AppRunnerScenarioExtensions.cs
CommandDotNet.Tests/CommandDotNet.NewerReleasesAlerts/NewReleaseAlertOnGitHubTests.cs
CommandDotNet.sln
CommandDotNet/Builders/AppInfo.cs
Directory.Build.props

at some point the version started resolving with a build number. trimmed the build number to keep parity.

support net8.0 and fix version resolution

---

CommandDotNet.Tests/FeatureTests/OnRunCompletedTests.cs
CommandDotNet/AppRunner.cs

an attempt to verify #488. 
@Sibusten can you post a failing test or point to a repo where this is failing?  I updated a test that seems to verify OnRunCompleted is called only after the pipeline is executed.  I might be missing something.

verify OnRunCompleted waits for pipeline to complete
