- CommandDotNet/MicrosoftCommandLineUtils/PipedInput.cs
@bilal-fazlani   This is a class I've used for console apps for a couple of projects.  Would you like to include it in this tool?
> add helper for getting piped input

- CommandDotNet.Tests/ModelTests.cs
- CommandDotNet.Tests/TestCases/ModelTests.ModelTests.Input.json
- CommandDotNet/ArgumentInfoCreator.cs
- CommandDotNet/ArgumentMerger.cs
- CommandDotNet/Extensions/TypeExtensions.cs
@bilal-fazlani  this will close #49.
> Issue 49 nesting models

- CommandDotNet/AppCreator.cs
@bilal-fazlani  After thinking about this use case and looking at the code, I think this is a simple solution that will unblock @erdmenchen. 
The framework only used the assembly in 2 places.
1. To get the app names if ApplicationMetadataAttribute wasn't set.  I changed that code to only use the assembly when needed and to fall back to "..." when the assembly is null.  I wasn't sure what other value to use.  Since this displays for help, instead of showing `dotnet someapp.dll cmdname` it will show `... cmdname`.   I thought about an empty string but wondered if that would make it easier to think a bug occurred.  
2. To get the version info.  I throw an exception if the assembly is null.  I thought about not enabling versioning but it wouldn't be obvious to devs why it wasn't working. …
> #65 - fix null ref when EntryAssembly is null

- CommandDotNet/MicrosoftCommandLineUtils/CommandLineApplication.cs
this fixes the incorrect command name in the usage from issue #74 .   
I'm pushing a test in another PR because I don't like the pattern and I want the fix to go in even if the test doesn't.
> Issue 74 command name

- CommandDotNet.Tests/BddTests/Apps/SingleCommandApp.cs
- CommandDotNet.Tests/BddTests/TestScenarios/SingleCommandAppDetailedHelpScenarios.cs
> add option and arg descriptions to SingleCommandApp

- CommandDotNet.Tests/BddTests/TestScenarios/OptionalParamsScenarios.cs
- CommandDotNet/Extensions/ObjectExtensions.cs
- CommandDotNet/HelpGeneration/DetailedHelpTextProvider.cs
- CommandDotNet/ValueMachine.cs
Includes bdd scenario verifying the fix.
> closes #97 - fix NullRef for optional string param

- CommandDotNet.Tests/BddTests/TestScenarios/FlagScenarios.cs
- README.md
fix readme example, adding [Option] attribute
> 5 add scenario for flags FlagScenarios

- CommandDotNet.Tests/AppRunnerResult.cs
- CommandDotNet.Tests/BddTests/Apps/SingleCommandApp.cs
- CommandDotNet.Tests/BddTests/Apps/SubCommandApp.cs
- CommandDotNet.Tests/BddTests/Framework/ScenarioThen.cs
- CommandDotNet.Tests/BddTests/ScenarioTests.cs
- CommandDotNet.Tests/BddTests/TestScenarios/FlagScenarios.cs
- CommandDotNet.Tests/BddTests/TestScenarios/GlobalOptionsInheritedScenarios.cs
- CommandDotNet.Tests/BddTests/TestScenarios/GlobalOptionsScenarios.cs
- CommandDotNet.Tests/BddTests/TestScenarios/OptionalParamsScenarios.cs
- CommandDotNet.Tests/BddTests/TestScenarios/SingleCommandAppDetailedHelpScenarios.cs
- CommandDotNet.Tests/BddTests/TestScenarios/SubCommandScenarios.cs
- CommandDotNet.Tests/Utils/TestOutputs.cs
- CommandDotNet/Extensions/ObjectExtensions.cs
- CommandDotNet/HelpGeneration/DetailedHelpTextProvider.cs
- CommandDotNet/TypeDescriptors/ArgumentTypeDescriptors.cs
- CommandDotNet/ValueMachine.cs
- README.md
includes some updates to the scenario test framework
for verifying help text parts w/ line endings and ending
in whitespaces
> 2 Adding sub-command help tests

- CommandDotNet.Tests/FeatureTests/CustomArgumentTypeDescriptors.cs
- CommandDotNet/TypeDescriptors/ArgumentTypeDescriptors.cs
fixed typo in error message
stop printing stack trace for this error since
it won't help the developer.
> feature tests for ArgumentTypeDescriptors (without version disabled changes)

- CommandDotNet.Tests/FeatureTests/DefaultCommandMethod.cs
- CommandDotNet.Tests/FeatureTests/ExceptionHandlingTests.cs
- CommandDotNet/AppCreator.cs
- CommandDotNet/Attributes/ApplicationMetadataAttribute.cs
- CommandDotNet/CommandCreator.cs
- CommandDotNet/HelpGeneration/BasicHelpTextProvider.cs
- CommandDotNet/HelpGeneration/DetailedHelpTextProvider.cs
- CommandDotNet/IApplicationMetadata.cs
- CommandDotNet/MicrosoftCommandLineUtils/CommandLineApplication.cs
- CommandDotNet/MicrosoftCommandLineUtils/CommandOption.cs
- CommandDotNet/Models/CommandInfo.cs
> default methods can define arguments

- CommandDotNet.Tests/FeatureTests/Arguments/EnumerableArgTypes.cs
- README.md
> show IEnumerable<T> is a valid argument type

- CommandDotNet.Tests/FeatureTests/CommandInvocatorTest.cs
- CommandDotNet.Tests/ScenarioFramework/ScenarioVerifier.cs
- CommandDotNet.Tests/StringValueParserTests.cs
- CommandDotNet.Tests/Utils/AppRunnerTestExtensions.cs
- CommandDotNet.Tests/Utils/StringExtensions.cs
- CommandDotNet/AppCreator.cs
- CommandDotNet/MicrosoftCommandLineUtils/CommandLineApplication.cs
some minor changes in preparation for adding directives and profiling parsing vs execution
> Refactoring prep

- CommandDotNet/AppRunner.cs
- CommandDotNet/IoCExtensions.cs
moving the extension method broke the other
nuget dependencies
> revert breaking change for #143

- CommandDotNet.Tests/FeatureTests/Arguments/BigArgumentsSets.cs
- CommandDotNet.Tests/Utils/StringExtensions.cs
I was nervous the dictionary and hashset
could lose order.  They didn't with this set
which reduces the priority of #72 for me.
It can wait until other infrastructure updates
make this easier to change
> test big argument sets work

- docs/argument-models.md
- docs/fluent-validation-for-argument-models.md
Adding more details for argument models, including the caveat that order for arguments is not guaranteed.  I'll update the argument/operand terminology in the v3 branch.
> enrich the documentation for argument models

- .gitignore
- CommandDotNet.TestTools/AppRunnerTestExtensions.cs
- CommandDotNet.Tests/AppRunnerScenarioExtensions.cs
- CommandDotNet.Tests/CommandDotNet.Tests.csproj.user
- CommandDotNet.Tests/FeatureTests/CancellationTokenTests.cs
- CommandDotNet.Tests/FeatureTests/ConstructorInjectionTests.cs
- CommandDotNet.Tests/FeatureTests/EnabledMiddlewareScenarios/OverridingDefaultValuesScenarios.cs
- CommandDotNet.Tests/FeatureTests/EnabledMiddlewareScenarios/SetDefaultsTestMiddleware.cs
- CommandDotNet/AppConfigBuilder.cs
- CommandDotNet/AppRunner.cs
- CommandDotNet/Builders/DependencyResolverMiddleware.cs
- CommandDotNet/ClassModeling/BindValuesMiddleware.cs
- CommandDotNet/ClassModeling/ClassModelingMiddleware.cs
- CommandDotNet/Extensions/MemberInfoExtensions.cs
- CommandDotNet/Extensions/TypeExtensions.cs
- CommandDotNet/IArgument.cs
- CommandDotNet/Parsing/IParser.cs
- CommandDotNet/Parsing/ListParser.cs
- CommandDotNet/Parsing/SingleValueParser.cs
- CommandDotNet/Tokens/CommandLineStringSplitter.cs
- CommandDotNet/Tokens/ICommandLineStringSplitter.cs
Fix CancellationToken usage and improve the experience for setting CustomHelpProvider, DependencyProvider & Console
> Beta v3/preview3

- CommandDotNet.Example/CommandDotNet.Example.csproj
- CommandDotNet.Example/Program.cs
- CommandDotNet.FluentValidation/CommandDotNet.FluentValidation.csproj
- CommandDotNet.FluentValidation/FluentValidationMiddleware.cs
- CommandDotNet.FluentValidation/ModelValidator.cs
- CommandDotNet.Tests/CommandDotNet.Tests.csproj
- CommandDotNet.Tests/FeatureTests/Arguments/ModelValidationTests.cs
- CommandDotNet.sln
- CommandDotNet/AppRunnerConfigExtensions.cs
extracting fluent validation into a separate package
> Beta v3/extract fluent validation

- .gitignore
- CommandDotNet.Example/CommandDotNet.Example.csproj
- CommandDotNet.Example/Examples.cs
- CommandDotNet.Example/build-win10-x64-exe.bat
- CommandDotNet.Tests/FeatureTests/Help/UsageAppNameStylesTests.cs
- CommandDotNet.sln
- CommandDotNet/Help/HelpBuilderExtensions.cs
- CommandDotNet/Help/HelpTextProvider.cs
- docs/Extensibility/help.md
fixes #197 and  #179 posted by @asymetrixs
> 197 self contained exe

- CommandDotNet.TestTools/TestToolsLogProvider.cs
- CommandDotNet.Tests/FeatureTests/TypeSuggestionsTests.cs
- CommandDotNet.Tests/FeatureTests/TypoSuggestions_GetSuggestions_Tests.cs
- CommandDotNet.Tests/UnitTests/Parsing/LevenshteinDistanceTests.cs
- CommandDotNet.Tests/Utils/AssertionExtensions.cs
- CommandDotNet/AppRunnerConfigExtensions.cs
- CommandDotNet/Execution/MiddlewareSteps.cs
- CommandDotNet/Parsing/CommandParser.cs
- CommandDotNet/Parsing/CommandParsingException.cs
- CommandDotNet/Parsing/Levenshtein.cs
- CommandDotNet/Parsing/TypoSuggestionsMiddleware.cs
- docs/Middleware/prompting.md
- docs/Middleware/typo-suggestions.md
- mkdocs.yml
> offer context based alternatives for miss typed arguments

- CommandDotNet.Example/CommandDotNet.Example.csproj
- CommandDotNet.FluentValidation/CommandDotNet.FluentValidation.csproj
- CommandDotNet.GitHubReleases/CommandDotNet.NewerReleasesAlerts.csproj
- CommandDotNet.IoC.Autofac/CommandDotNet.IoC.Autofac.csproj
- CommandDotNet.IoC.MicrosoftDependencyInjection/CommandDotNet.IoC.MicrosoftDependencyInjection.csproj
- CommandDotNet.IoC.SimpleInjector/CommandDotNet.IoC.SimpleInjector.csproj
- CommandDotNet.NameCasing/CommandDotNet.NameCasing.csproj
- CommandDotNet.TestTools/CommandDotNet.TestTools.csproj
- CommandDotNet.Tests/CommandDotNet.FluentValidation/ModelValidationTests.cs
- CommandDotNet.Tests/CommandDotNet.Tests.csproj
- CommandDotNet.Tests/FeatureTests/ArgumentDefaults/DefaultFromAppSettingsTests.cs
- CommandDotNet.Tests/FeatureTests/ArgumentDefaults/DefaultFromEnvVarsTests.cs
- CommandDotNet.Tests/FeatureTests/CustomArgumentTypeDescriptorTests.cs
- CommandDotNet/CommandDotNet.csproj
- Directory.Build.props
it's obvious what is common between the projects
and easier to upgrade and use new language features
across projects
> extract common build properties to Directory.Build.props

- docs/DefiningCommands/arguments.md
PR for iterating since local docs aren't working
> Docs for guarantee-operand-order branch

- CommandDotNet.TestTools/AppRunnerTestExtensions.cs
- CommandDotNet.TestTools/AssertionExtensions.cs
- CommandDotNet.Tests/FeatureTests/Arguments/AppsSettingsBoolModeTests.cs
- CommandDotNet.Tests/FeatureTests/Arguments/BasicParseTests.cs
- CommandDotNet.Tests/FeatureTests/SuggestionRankingExtensionsTests.cs
- CommandDotNet.Tests/FeatureTests/Suggestions/AllowedValuesTypoSuggestionsTests.cs
- CommandDotNet.Tests/FeatureTests/Suggestions/CafeApp.cs
- CommandDotNet.Tests/FeatureTests/Suggestions/TypoSuggestionsTests.cs
- CommandDotNet.Tests/FeatureTests/TypoSuggestionsTests.cs
- CommandDotNet.Tests/UnitTests/DefinedMiddlewareStepsTests.cs
- CommandDotNet.Tests/UnitTests/Parsing/LevenshteinDistanceTests.cs
- CommandDotNet/AppRunnerConfigExtensions.cs
- CommandDotNet/Execution/MiddlewareStep.cs
- CommandDotNet/Execution/MiddlewareSteps.cs
- CommandDotNet/Extensions/ServicesExtensions.cs
- CommandDotNet/Parsing/CommandParser.cs
- CommandDotNet/Parsing/CommandParsingException.cs
- CommandDotNet/Parsing/Typos/Levenshtein.cs
- CommandDotNet/Parsing/Typos/SuggestionRankingExtensions.cs
- CommandDotNet/Parsing/Typos/TypoSuggestionsMiddleware.cs
- CommandDotNet/Parsing/UnrecognizedArgumentCommandParsingException.cs
- CommandDotNet/Parsing/UnrecognizedValueCommandParsingException.cs
- CommandDotNet/Tokens/TokenCollection.cs
- CommandDotNet/Tokens/Tokenizer.cs
- docs/Help/typo-suggestions.md
- docs/ReleaseNotes/CommandDotNet.TestTools.md
- docs/ReleaseNotes/CommandDotNet.md
- docs/ReleaseNotes/roadmap.md
@bilal-fazlani with this PR, TypoSuggest will suggest for argument values like enums.
> Typo suggest allowed values

- CommandDotNet.Tests/CommandDotNet.FluentValidation/ModelValidationTests.cs
- CommandDotNet.Tests/FeatureTests/Arguments/Operands_DefinedAsArgModel_Defaults_Tests.cs
- CommandDotNet.Tests/FeatureTests/Arguments/Operands_DefinedAsArgModel_NoDefaults_Tests.cs
- CommandDotNet/ClassModeling/Definitions/PropertyArgumentDef.cs
- CommandDotNet/Command.cs
I thought the outcome would change arity calculation
but it didn't so... Yay.
Added tests to verify behavior
> cleanup HasDefaultValue logic for PropertyArgumentDef

- CommandDotNet.DataAnnotations/CommandDotNet.DataAnnotations.csproj
- CommandDotNet.DataAnnotations/DataAnnotationsMiddleware.cs
- CommandDotNet.DataAnnotations/MiddlewareSteps.cs
- CommandDotNet.FluentValidation/CommandDotNet.FluentValidation.csproj
- CommandDotNet.FluentValidation/FluentValidationMiddleware.cs
- CommandDotNet.Tests/CommandDotNet.DataAnnotations/DataAnnotationsValidationTests.cs
- CommandDotNet.Tests/CommandDotNet.Tests.csproj
- CommandDotNet.sln
- docs/Arguments/data-annotations-validation.md
- docs/features.md
- mkdocs.yml
- created project CommandDotNet.DataAnnotations
- add initial implementation with tests
Does *not* create a ValidationContext and only validates
attributes for specific argument values.
Class level validations likely won't work which should only
affect argument models
closes #253
> create DataAnnotations middleware/project

- CommandDotNet.Tests/FeatureTests/ParseTests/SubcommandParseTests.cs
- CommandDotNet/Parsing/CommandParser.cs
> give suggestion when subcommand is prefixed as option

- CommandDotNet/NamedAttribute.cs
- CommandDotNet/OptionAttribute.cs
- CommandDotNet/PositionalAttribute.cs
- docs/Arguments/arguments.md
> allow optional named and positional attributes

- .github/workflows/release.yml
- .github/workflows/test.yml
- CommandDotNet.Example.Tests/CommandDotNet.Example.Tests.csproj
- CommandDotNet.Example/CommandDotNet.Example.csproj
- CommandDotNet.Tests/CommandDotNet.Tests.csproj
- CommandDotNet.sln
- Directory.Build.props
We've decided it's time to let go of netstandard2.0
All future development will target the latest languages
> upgrade CommandDotNet to net5.0

- CommandDotNet.DocExamples/Arguments/Arguments/Passwords.cs
- CommandDotNet.TestTools/Prompts/Answer.cs
- CommandDotNet.TestTools/Prompts/ListAnswer.cs
- CommandDotNet.TestTools/Prompts/Respond.cs
- CommandDotNet.TestTools/Prompts/TextAnswer.cs
- CommandDotNet.Tests/FeatureTests/ParseDirective/ParseReporter_InputValues_Tests.cs
- CommandDotNet.Tests/FeatureTests/Prompting/PromptForMissingArgumentTests.cs
- CommandDotNet.Tests/FeatureTests/Prompting/PromptForMissingArgumentTests_Password.cs
- CommandDotNet.Tests/FeatureTests/Prompting/PromptInteractionTests.cs
obsoleted TextAnswer and ListAnswer
while using these for the first time in a while
I realized this is more discoverable
> add ctors for TextAnswer and ListAnswer to Answer

- CommandDotNet.Example/single-file-publish.sh
- CommandDotNet.Example/single-file-run.sh
- CommandDotNet/Builders/AppInfo.cs
include scripts to simplify creation and manual testing
> #418 get version for single-file apps

- CommandDotNet.DocExamples/BashSnippets/command_logger_appconfig_exe.bash
- CommandDotNet.DocExamples/BashSnippets/command_logger_custom_attribute_disabled.bash
- CommandDotNet.DocExamples/BashSnippets/command_logger_custom_attribute_enabled.bash
- CommandDotNet.DocExamples/BashSnippets/command_logger_default_directive.bash
- CommandDotNet.DocExamples/BashSnippets/command_logger_default_no_directive.bash
- CommandDotNet.DocExamples/BashSnippets/command_logger_include_machine_and_user_exe.bash
- CommandDotNet.DocExamples/BashSnippets/command_logger_root_option_exe.bash
- CommandDotNet.DocExamples/Diagnostics/Command_Logger.cs
- CommandDotNet.DocExamples/Diagnostics/Exceptions.cs
- CommandDotNet.Example/Program.cs
- CommandDotNet.Tests/CommandDotNet.CommandLogger/CommandLoggerTests.cs
- CommandDotNet/AppRunnerConfigExtensions.cs
- CommandDotNet/Diagnostics/CommandLogger.cs
- CommandDotNet/Diagnostics/CommandLoggerMiddleware.cs
- docs/Diagnostics/command-logger.md
- docs/Diagnostics/exceptions.md
- docs/GettingStarted/getting-started-500-interceptors.md
> update CommandLogger documentation

- CommandDotNet.DocExamples/Arguments/Values/Piped_Arguments.cs
- CommandDotNet.DocExamples/BashSnippets/command_logger_appconfig_exe.bash
- CommandDotNet.DocExamples/BashSnippets/piped_arguments_options_notify.bash
- CommandDotNet.DocExamples/Diagnostics/Command_Logger.cs
- CommandDotNet.Example/Commands/Pipes.cs
- CommandDotNet.Tests/FeatureTests/Arguments/PipedInputTargetTests.cs
- CommandDotNet/ArgumentAppSettings.cs
$ was causing problems in bash
> change default pipe target from $* to ^

- CommandDotNet.DocExamples/BashSnippets/command_logger_appconfig_exe.bash
- CommandDotNet.DocExamples/Diagnostics/Command_Logger.cs
- CommandDotNet.Tests/FeatureTests/ClassCommands/InheritFromBaseClassesTests.cs
- CommandDotNet/AppSettings.cs
- CommandDotNet/ArgumentAppSettings.cs
- CommandDotNet/ClassModeling/Definitions/ClassCommandDef.cs
- CommandDotNet/CommandAppSettings.cs
- CommandDotNet/Extensions/TypeExtensions.cs
- docs/Commands/commands.md
- docs/ReleaseNotes/CommandDotNet.md
🚧 Requires tests, updated docs and release notes.
> Enable commands to be inherited from base classes

- CommandDotNet.NameCasing/Case.cs
- CommandDotNet.NameCasing/CaseChanger.cs
- CommandDotNet.NameCasing/HumanizerAppRunnerExtensions.cs
- CommandDotNet.TestTools/InvocationInfo.cs
- CommandDotNet.Tests/CommandDotNet.DataAnnotations/DataAnnotationsValidationTests.cs
- CommandDotNet.Tests/CommandDotNet.NameCasing/CaseChangerTests.cs
- CommandDotNet.Tests/CommandDotNet.NameCasing/CaseTests.cs
- CommandDotNet/ClassModeling/Definitions/MethodDef.cs
and verify DataAnnotations honors namecasing
> support snake_case

- .github/workflows/release.yml
- .github/workflows/test.yml
- CommandDotNet/Extensions/TypeExtensions.cs
- Directory.Build.props
- docs/OtherFeatures/name-casing.md
- docs/ReleaseNotes/CommandDotNet.DataAnnotations.md
- docs/ReleaseNotes/CommandDotNet.FluentValidation.md
- docs/ReleaseNotes/CommandDotNet.IoC.Autofac.md
- docs/ReleaseNotes/CommandDotNet.IoC.MicrosoftDependencyInjection.md
- docs/ReleaseNotes/CommandDotNet.IoC.SimpleInjector.md
- docs/ReleaseNotes/CommandDotNet.NameCasing.md
- docs/ReleaseNotes/CommandDotNet.NewerReleasesAlerts.md
- docs/ReleaseNotes/CommandDotNet.Spectre.Testing.md
- docs/ReleaseNotes/CommandDotNet.Spectre.md
- docs/ReleaseNotes/CommandDotNet.TestTools.md
- docs/ReleaseNotes/CommandDotNet.md
update release notes
upgrade to c#11
support dotnet 6 & 7
> prep for new packages

- CommandDotNet.TestTools/AppRunnerTestConfigExtensions.cs
- CommandDotNet/Localization/CultureDirective.cs
found two other cases where we needed to await next
> verify OnRunCompleted waits for pipeline to complete
